           
name: Create Tag And Release
on:
  push:
    branches:
      - master
jobs:
  createTagAndRelease:
    runs-on: ubuntu-latest
    name: Create Tag And Release
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set Tag Name
        run: |           
          git fetch --tags
          newestTag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "newestTag=$newestTag"
          newTag=$(echo "$newestTag" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
          echo "newTag=$newTag"
          echo "newTagName=$newTag" >> $GITHUB_ENV
      
      - name: Create tag & Release
        uses: actions/github-script@v6
        # https://docs.github.com/en/rest/reference/releases#create-a-release
        with:
          script: |
            console.log("newTagName=${{ env.newTagName }}")
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ env.newTagName }}",
              name: "${{ env.newTagName }}",
              body: "Version ${{ env.newTagName }}",
              target_commitish: context.sha
            });
            
