name: Run Tests

on:
  workflow_dispatch:
    inputs:
      useComplexSwagger:
        description: 'Use complexSwagger.json'
        required: false
        default: 'true'
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

env:
  OPENAPI_TOOLKIT_TESTFILE: "${{ github.workspace }}/.github/complexSwagger.json"
  DOTNET_NOLOGO: true

jobs:
  test-typescript-axios:
    name: Test Typescript Axios
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
        with:
          useComplexSwagger: ${{ github.event.inputs.useComplexSwagger }}
      - run: npm run test:typescript-axios

  test-typescript-models:
    name: Test Typescript Models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
        with:
          useComplexSwagger: ${{ github.event.inputs.useComplexSwagger }}
      - run: npm run test:typescript-models

  test-typescript-reactquery:
    name: Test Typescript ReactQuery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
        with:
          useComplexSwagger: ${{ github.event.inputs.useComplexSwagger }}
      - run: npm run test:typescript-react-query
        
  test-csharp:
    name: Test C#
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
        with:
          useComplexSwagger: ${{ github.event.inputs.useComplexSwagger }}

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        
      - run: npm run test:csharp

  test-csharp-nullable-false:
    name: Test C# nullable false
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Prepare Environment
          uses: ./.github/actions/prepare-env
          with:
            useComplexSwagger: ${{ github.event.inputs.useComplexSwagger }}
  
        - name: Install .NET
          uses: actions/setup-dotnet@v3
          
        - run: npm run test:csharp2
        
  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
        with:
          useComplexSwagger: ${{ github.event.inputs.useComplexSwagger }}
          
      - name: Install Python
        uses: actions/setup-python@v4

      - run: pip install pylint requests
      - run: npm run test:python

  test-go:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
        with:
          useComplexSwagger: ${{ github.event.inputs.useComplexSwagger }}
      - run: npm run test:go
        
  test-go-server:
    name: Test Go Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
        with:
          useComplexSwagger: ${{ github.event.inputs.useComplexSwagger }}
      - run: npm run test:go-server
