name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
env:
  OPENAPI_TOOLKIT_TESTFILE: "${{ github.workspace }}/swagger.json"
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare Environment
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
        
      - name: download swagger file
        run: curl https://petstore.swagger.io/v2/swagger.json -o $OPENAPI_TOOLKIT_TESTFILE

      - name: install dependencies
        run: rm -rf .npmrc && npm i

      - name: build 
        run: npm run build

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  test-typescript:
    name: Test Typescript
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm run test:typescript

  test-typescript-reactquery:
    name: Test Typescript ReactQuery
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm run test:typescript-react-query
        
  test-csharp:
    name: Test C#
    runs-on: ubuntu-latest
    needs: [ prepare ]
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: install dotnet
        uses: actions/setup-dotnet@v2
      - run: npm run test:csharp
        
  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm run test:python
        
  test-go:
    name: Test Go
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm run test:go
        
  test-go-server:
    name: Test Go Server
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm run test:go-server
