name: Run Tests

on:
  workflow_dispatch:
    inputs:
      useComplexSwagger:
        description: 'Use complexSwagger.json'
        required: false
        default: 'true'
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

env:
  OPENAPI_TOOLKIT_TESTFILE: "${{ github.workspace }}/.github/complexSwagger.json"

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare Environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: Set useComplexSwagger conditions
        id: useComplexSwagger
        run: |
          contains_complex_ut_label="false"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            contains_complex_ut_label="${{ contains(toJson(github.event.pull_request.labels.*.name), 'complex-ut') }}"
          fi
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.useComplexSwagger }}" == "true" ]]; then
            echo "useComplexSwagger=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" && ( "${{ github.event.pull_request.title }}" == *"+ complex ut"* || "$contains_complex_ut_label" == "true" ) ]]; then
            echo "useComplexSwagger=true" >> $GITHUB_OUTPUT
          else
            echo "useComplexSwagger=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Download Swagger file
        run: curl https://petstore.swagger.io/v2/swagger.json -o $OPENAPI_TOOLKIT_TESTFILE
        if: steps.useComplexSwagger.outputs.useComplexSwagger == 'false'

      - name: Install dependencies
        run: rm -rf .npmrc && npm i

      - name: Build
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}
          path: ${{ github.workspace }}

  test-typescript-axios:
    name: Test Typescript Axios
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}

      - run: npm run test:typescript-axios

  test-typescript-models:
    name: Test Typescript Models
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}

      - run: npm run test:typescript-models

  test-typescript-reactquery:
    name: Test Typescript ReactQuery
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}

      - run: npm run test:typescript-react-query
        
  test-csharp:
    name: Test C#
    runs-on: ubuntu-latest
    needs: [ prepare ]
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - run: npm run test:csharp

  test-csharp-nullable-false:
    name: Test C# nullable false
    runs-on: ubuntu-latest
    needs: [ prepare ]
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - run: npm run test:csharp2
        
  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}

      - name: Install Python
        uses: actions/setup-python@v4

      - run: pip install pylint requests
      - run: npm run test:python

  test-go:
    name: Test Go
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}

      - run: npm run test:go
        continue-on-error: true
        
  test-go-server:
    name: Test Go Server
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ github.sha }}

      - run: npm run test:go-server
        continue-on-error: true
